import type { CartResponse, Product, ProfileResponse, ReviewsResponse, WishlistResponse } from "./types";

export const fallbackProducts: Product[] = [
  {
    slug: "heritage-mango-pickle",
    title: "Heritage Mango Pickle",
    subtitle: "Sun-dried purity",
    category: "Pickles",
    badge: "Sun-dried",
    description:
      "Crafted using handpicked raw mangoes, sun-dried naturally, and preserved in cold-pressed mustard oil with a blend of heritage spices. A tangy, nostalgic taste of home.",
    storyTitle: "Aged in Tradition, Sun-Kissed for Soul",
    story: [
      "Our Heritage Mango Pickle is not manufactured; it is nurtured. Rooted in a generations-old grandmother's recipe, every batch begins with the finest raw mangoes, sliced and marinated in sea salt and turmeric, then laid out under the golden Indian sun.",
      "We age our pickles in traditional ceramic martabans, allowing the cold-pressed mustard oil and aromatic spices like fenugreek and fennel to weave a complex, tangy flavor profile. Absolutely zero artificial preservatives-just time, nature, and heritage.",
    ],
    price: 350,
    salePrice: 349,
    originalPrice: 450,
    cartUnitPrice: 450,
    pack: "400g Jar",
    rating: 4.9,
    reviewCount: 128,
    sizeOptions: ["400g Jar", "800g Jar"],
    tags: ["No Added Preservatives", "Gluten-Free", "Vegan", "Traditionally Fermented"],
    ingredients: [
      { icon: "eco", title: "Raw Mangoes", text: "Crisp, farm-fresh" },
      { icon: "water_drop", title: "Mustard Oil", text: "Cold-pressed pure" },
      { icon: "spa", title: "Heritage Spices", text: "Fenugreek & Fennel" },
      { icon: "grain", title: "Sea Salt", text: "Unrefined preservation" },
    ],
    benefits: ["100% Sun-Dried Naturally", "Sourced from Local Organic Farms"],
    isListed: true,
    sortOrder: 1,
  },
  {
    slug: "kachi-ghani-mustard-oil",
    title: "Kachi Ghani Mustard Oil",
    subtitle: "Cold-pressed heritage",
    category: "Oils",
    badge: "Cold-pressed",
    description: "Traditional wooden churned, unrefined, 1L.",
    price: 420,
    cartUnitPrice: 390,
    pack: "1 Litre Glass Bottle",
    rating: 5,
    reviewCount: 245,
    sizeOptions: ["1L Bottle"],
    tags: ["Cold-Pressed", "Unrefined", "Wood Pressed"],
    ingredients: [{ icon: "water_drop", title: "Mustard Seeds", text: "Single-origin, wood pressed" }],
    benefits: ["Pressed in Wooden Ghani", "No Chemical Refining"],
    isListed: true,
    sortOrder: 2,
  },
  {
    slug: "artisanal-multigrain-atta",
    title: "Artisanal Multigrain Atta",
    subtitle: "Stone-ground nutrition",
    category: "Flours",
    badge: "Stone-ground",
    description: "Stone-ground daily. 5kg pack.",
    price: 580,
    pack: "5kg Paper Sack",
    rating: 4,
    reviewCount: 89,
    sizeOptions: ["5kg Sack"],
    tags: ["Stone-Ground", "High Fiber", "No Additives"],
    ingredients: [{ icon: "grass", title: "Heritage Grains", text: "Wheat, jowar, bajra and ragi" }],
    benefits: ["Stone-Ground in Small Batches", "Balanced Multigrain Blend"],
    isListed: true,
    sortOrder: 3,
  },
  {
    slug: "a2-gir-cow-ghee",
    title: "A2 Gir Cow Ghee",
    subtitle: "Bilona method. 500ml jar.",
    category: "Ghee",
    badge: "Out of Season",
    description: "Traditional bilona method ghee made from A2 Gir cow milk.",
    price: 1200,
    pack: "500ml Jar",
    rating: 0,
    reviewCount: 0,
    sizeOptions: ["500ml Jar"],
    tags: ["Bilona Method", "Seasonal"],
    ingredients: [{ icon: "local_drink", title: "A2 Milk", text: "Cultured and hand churned" }],
    benefits: ["Small Seasonal Batches"],
    isListed: false,
    sortOrder: 4,
  },
];

export const fallbackCart: CartResponse = {
  items: [
    {
      productSlug: "heritage-mango-pickle",
      quantity: 1,
      unitPrice: 450,
      unitPriceLabel: "₹450",
      lineTotal: 450,
      lineTotalLabel: "₹450",
      product: fallbackProducts[0],
    },
    {
      productSlug: "kachi-ghani-mustard-oil",
      quantity: 2,
      unitPrice: 390,
      unitPriceLabel: "₹390",
      lineTotal: 780,
      lineTotalLabel: "₹780",
      product: fallbackProducts[1],
    },
  ],
  totals: {
    itemCount: 3,
    subtotal: 1230,
    subtotalLabel: "₹1,230",
    shipping: 80,
    shippingLabel: "₹80",
    total: 1310,
    totalLabel: "₹1,310",
  },
};

export const fallbackWishlist: WishlistResponse = {
  items: [
    { productSlug: "artisanal-multigrain-atta", status: "IN STOCK", actionLabel: "Add to Cart", product: fallbackProducts[2] },
    { productSlug: "kachi-ghani-mustard-oil", status: "LOW STOCK", actionLabel: "Add to Cart", product: fallbackProducts[1] },
    { productSlug: "a2-gir-cow-ghee", status: "OUT OF SEASON", actionLabel: "Notify Me", product: fallbackProducts[3] },
  ],
};

export const fallbackReviews: ReviewsResponse = {
  summary: { average: 4.5, count: 2 },
  items: [
    {
      _id: "fallback-review-1",
      productSlug: "heritage-mango-pickle",
      rating: 5,
      title: "Tastes like a summer kept in a jar",
      comment: "The mango pieces are firm, the oil is fragrant, and the spice balance feels genuinely homemade.",
      verifiedPurchase: true,
      user: { name: "Prasoon Kumar", avatarInitials: "PK" },
    },
    {
      _id: "fallback-review-2",
      productSlug: "heritage-mango-pickle",
      rating: 4,
      title: "Beautifully traditional",
      comment: "Loved the sun-dried tang and mustard aroma. A little sharper than expected, in the best way.",
      verifiedPurchase: true,
      user: { name: "Gaon Veda Customer", avatarInitials: "GV" },
    },
  ],
};

export const fallbackProfile: ProfileResponse = {
  user: {
    _id: "fallback-user",
    name: "Prasoon Kumar",
    email: "prasoon@example.com",
    phone: "+91 98765 43210",
    avatarInitials: "PK",
    loyaltyPoints: 240,
    addresses: [
      {
        label: "Home",
        recipient: "Prasoon Kumar",
        line1: "221B Heritage Lane",
        city: "Gurugram",
        state: "Haryana",
        postalCode: "122001",
        country: "India",
        phone: "+91 98765 43210",
        isDefault: true,
      },
    ],
    preferences: { newsletter: true, smsUpdates: true },
  },
  stats: {
    cartItems: fallbackCart.totals.itemCount,
    wishlistItems: fallbackWishlist.items.length,
    orderCount: 0,
    loyaltyPoints: 240,
  },
  recentOrders: [],
};
